### ISSUE TITLE
Demo link in the repository description is broken

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/app-extension-qpdfviewer#1]
Demo links were fixed in README but stayed the same in repository description.

Broken link: https://quasarframework.github.io/app-extension-qpdfviewer/demo/dist/spa/#/
Working link: https://quasarframework.github.io/app-extension-qpdfviewer/

**Comment by yusufkandemir** [comment]
This problem also exists in following repositories:
quasarframework/app-extension-qoverlay
quasarframework/app-extension-qenv
quasarframework/app-extension-qflashcard
quasarframework/app-extension-qactivity
quasarframework/app-extension-dotenv
quasarframework/app-extension-qiconpicker
quasarframework/app-extension-qscroller

**Comment by hawkeye64** [comment]
Thank you so much for bring this to my attention. :heart:

**Comment by hawkeye64** [comment]
I added QCalendar and QMediaplayer in there as well. If you see any issues, let me know. And, thanks again!
