### ISSUE TITLE
quasar/qpdfviewer is not compatible with @quasar/app v3.0.3

### ISSUE THREAD

**Issue by teebeiz** [quasarframework/app-extension-qpdfviewer#100]
I Installed quasar/qpdfviewer into my quasar project and see the "Extension(@quasar/qpdfviewer): is not compatible with @quasar/app v3.0.3 Required version: ^1.0.0 || ^2.0.0" , How can I use this component, please help, Thank you.

**Comment by hawkeye64** [comment]
Please use the `next` branch.

```
quasar ext add @quasar/qpdfviewer@next
```

Notice the `@next`
