### ISSUE TITLE
[docs] - How to position qpdfviewer in QDialog

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qpdfviewer#11]
It was tricky to find a way how to position a pdf inside a QDialog. Because the bottom arrow of the pdf was hidden due to the QBar on the top of window (pdf is shifted out of the view area).
![image](https://user-images.githubusercontent.com/37825539/62688979-34b01c80-b9ca-11e9-879a-3f8cf8ae5621.png)

I don't know if it is a best way but was the only solution I found.

```html
<!-- parent component -->
<template>
  <q-dialog :maximized="$q.screen.lt.md" @hide="onDialogHide" ref="mediaContentDialog">

    <q-card class="no-scroll" style="background: yellow; min-width: 80vw; min-height: 80vh;">

      <q-bar class="bg-brand-light">
        <h5 class="text-brand-text">{{title}}</h5>
        <q-space></q-space>
        <q-btn @click="hide" color="white" flat icon="close"></q-btn>
      </q-bar>

      <pdf-content :src="src" :title="title"></pdf-content>
    </q-card>
  </q-dialog>
</template>
```

```html
<!-- children with q-pdfviewer --->
 <q-pdfviewer 
                 :src="src"
                 content-class="absolute shorten-pdf"
                 v-model="show"
    ></q-pdfviewer>
```
```css
<style scoped>
  .shorten-pdf{
    height: calc(100% - 30px);
  }
```
Result:
![image](https://user-images.githubusercontent.com/37825539/62688687-a045ba00-b9c9-11e9-8485-6fc06bd7e4fc.png)

Hope this information is helpful for users when positioning pdf inside a QDialog.

**Comment by hawkeye64** [comment]
Thanks for this! :heart: 
I hope to revamp the docs fairly soon and will be including various examples. Hope to incorporate this one in.

**Comment by mesqueeb** [comment]
@m0jimo I also had many problems with this.

This is my current method: https://github.com/quasarframework/app-extension-qpdfviewer/issues/8#issuecomment-517111243

**Comment by hawkeye64** [comment]
@m0jimo I have incorporated the QDialog example into the latest release (docs): https://qpdfviewer.netlify.app/developing/using-qpdfviewer
