### ISSUE TITLE
Yarn package 2.0.0-alpha.3 points to old build

### ISSUE THREAD

**Issue by Error07** [quasarframework/app-extension-qpdfviewer#113]
I noticed that in QPdfviewer.js this string starts with a "/":
Line 82 : ` src: '/pdfjs/web/viewer.html?file=' + encodeURIComponent(prop.src)`
This results in the content of pdfjs-directory not being found when using quasar build (error 404).
I was about to submit a issue or a pull request for that, when i noticed that the latest code in the repository is correct and at least 3 months old.

The funny thing is: When you do "yarn add @quasar/quasar-app-extension-qpdfviewer@next" you get the correct package (exactly one time!).
However, when you do "yarn add @quasar/quasar-app-extension-qpdfviewer@2.0.0-alpha.3" you get the faulty package.
"quasar ext add @quasar/qpdfviewer@next" does also deliver the faulty package. unfortunately.

All commands result in a identical package.json and yarn.lock, every other project member will download the wrong package when they execute yarn install, as the url in yarn.lock seems to be the same.
The url in yarn.lock is: https://registry.yarnpkg.com/@quasar/quasar-app-extension-qpdfviewer/-/quasar-app-extension-qpdfviewer-2.0.0-alpha.3.tgz#a6f8d199190ab8681e5d337ca430a1adbcac74d5

Can you maybe reupload the package or do something?

Greetings!
Keep up the good work

**Comment by hawkeye64** [comment]
Yes, this would seem to be the fix. I'll try to find time on the weekend. Thanks for reporting.

**Comment by hawkeye64** [comment]
This is fixed with the latest releases.

**Comment by Error07** [comment]
Hi @hawkeye64,
something still seems to be off.
The URL to the 2.0.0-alpha.4 still has the same issue with the extra "/" :
https://registry.yarnpkg.com/@quasar/quasar-app-extension-qpdfviewer/-/quasar-app-extension-qpdfviewer-2.0.0-alpha.4.tgz#8ff27f54706a75129e3904b3942cd70fa48b189a

**Comment by hawkeye64** [comment]
Are you using yarn or npm?

**Comment by hawkeye64** [comment]
I guess that would be yarn.
Maybe that's the way it indexes things. I don't know. Does using it in a "normal" way not work?
Try `quasar ext invoke @quasar/qpdfviewer` and let it do the re-install.

**Comment by Error07** [comment]
yes, i am using yarn. using it the normal way resulted in this, so i took a look at the URL's in the yarn.lock to make sure it's loading from a reasonable URL. 
unfortunately, the command you offered did not help.
