### ISSUE TITLE
onload - undefined

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qpdfviewer#12]
When opening a dialog with qpdfviewer I get following error (pdf is loaded):
```html
<q-pdfviewer 
                 :error="errorWithPdf"
                 :src="src"
                 content-class="absolute  shorten-pdf"
                 v-model="show"
    ></q-pdfviewer>
```
```js
  errorWithPdf() {
        return "test";
        // console.log("---evt", evt);
      }
```
![image](https://user-images.githubusercontent.com/37825539/62689198-a5efcf80-b9ca-11e9-9ce8-bbd75d1a421d.png)

If I remove the :error the error is doubled in cosole:
```html
   <q-pdfviewer
                 :src="src"
                 content-class="absolute shorten-pdf"
                 v-model="show"
    ></q-pdfviewer>
```
![image](https://user-images.githubusercontent.com/37825539/62689709-a177e680-b9cb-11e9-90d4-0d04a2cca87e.png)

Src for pdf is defined locally ```"../data/eContainerDemo/test.pdf"```.

**Comment by m0jimo** [comment]
Now I see it is duplicated with https://github.com/quasarframework/app-extension-qpdfviewer/issues/4

solution as suggested + :error:
```html
 <q-pdfviewer
                :error="nothing"
                 :src="src"
                 :closed="nothing"
                 :load="nothing"
                 content-class="absolute shorten-pdf"
                 v-model="show"
    ></q-pdfviewer>
```

**Comment by hawkeye64** [comment]
and https://github.com/quasarframework/app-extension-qpdfviewer/issues/8
