### ISSUE TITLE
can i use this in vue3？

### ISSUE THREAD

**Issue by PongChen** [quasarframework/app-extension-qpdfviewer#127]
⚠️  Extension(@quasar/qpdfviewer): is not compatible with @quasar/app-webpack v3.6.2. Required version: ^1.0.0 || ^2.0.0

**Comment by Gramok** [comment]
Hi, you need to install v2 beta for Quasar2/Vue3. Please check this: https://qpdfviewer.netlify.app/

**Comment by PongChen** [comment]
> Hi, you need to install v2 beta for Quasar2/Vue3. Please check this: https://qpdfviewer.netlify.app/

thanks very much
