### ISSUE TITLE
error-string - value not passed

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qpdfviewer#13]
If error-string has a value it is not passed to component.

![image](https://user-images.githubusercontent.com/37825539/62764444-317e6480-ba8e-11e9-933e-d91a2de40f15.png)

**Comment by hawkeye64** [comment]
Thanks for letting me know about this. It is actually a duplicate of https://github.com/quasarframework/app-extension-qpdfviewer/issues/8
