### ISSUE TITLE
File not found - Reload button reloads the whole application

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qpdfviewer#14]
If pdf is not found there is a button with Reload. It reloads the whole application. It'd be better to have a button only for reloading a file.

![image](https://user-images.githubusercontent.com/37825539/62764578-85894900-ba8e-11e9-8198-47e117d7e2da.png)

And the higher level could be a slot for custom component when the file is not found.

**Comment by hawkeye64** [comment]
I am afraid this isn't my work, but part of the HTML5 PDF rendering engine.
