### ISSUE TITLE
orimi.com (PDF URL) is blocked by my antivirus product.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/app-extension-qpdfviewer#15]
I get an AV warning that blocks orimi.com (PDF URL) from my antivirus product.

**Comment by tohagan** [comment]
Checked the URL https://www.orimi.com/pdf-test.pdf with https://www.virustotal.com/gui/home/url and URL blacklists it passes OK. Suspect my AV is over zealous.

**Comment by hawkeye64** [comment]
Yes, they can be over zealous for sure. That have to suspect everything.
