### ISSUE TITLE
Demo pdfs are failing to load

### ISSUE THREAD

**Issue by hailwood** [quasarframework/app-extension-qpdfviewer#18]
Hi @hawkeye64 

Just letting you know the the adobe hosted pdfs are failing to load on the demo page.
They must have updated their content security policies.

**Comment by hawkeye64** [comment]
yeah, probably. Thanks for letting me know. I'll have to put some local ones on the server.

**Comment by hawkeye64** [comment]
hmmm, they are all working for me. Perhaps you're getting blocked on your end?

![image](https://user-images.githubusercontent.com/10262924/63544080-77e9af80-c4e1-11e9-9556-4cabc359995b.png)

**Comment by hawkeye64** [comment]
I still need local pdfs tho

**Comment by hailwood** [comment]
Perhaps it's a browser thing?
Using google chrome here.

![image](https://user-images.githubusercontent.com/709773/63550540-006e5b80-c587-11e9-9462-dfbf17917e11.png)

```
Refused to display 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors *.adobe.com  http://adobe.lookbookhq.com https://adobe.lookbookhq.com http://adobeenterprise.lookbookhq.com https://adobeenterprise.lookbookhq.com".
about:blank:1 

Refused to display 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors *.adobe.com  http://adobe.lookbookhq.com https://adobe.lookbookhq.com http://adobeenterprise.lookbookhq.com https://adobeenterprise.lookbookhq.com".
about:blank:1 

Refused to display 'https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors *.adobe.com".
3content.js:150 

Error: Cannot set user agent for iframe with location different to this page
/app-extension-qpdfviewer/page5:1 

Refused to display 'https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

**Comment by hawkeye64** [comment]
I get this, but they still display. I wonder what the difference might be between our browsers (I am using Chrome):
![image](https://user-images.githubusercontent.com/10262924/63591591-639ec480-c56c-11e9-9738-01a30de51487.png)

**Comment by hailwood** [comment]
Ok yep, definitely my machine. Got a co-worker to check (running the same OS/browser as me) and they can see them all.

Very strange!
