### ISSUE TITLE
Download immediately triggered on Firefox for Android

### ISSUE THREAD

**Issue by stefanvanherwijnen** [quasarframework/app-extension-qpdfviewer#2]
When a page with the PDF viewer is opened (e.g. the demo) on Firefox for Android (both the current version as the preview version), the PDF is immediately downloaded.
I don't think any of the Android browsers have built in PDF viewing support, so it makes sense that it is not displayed. However, having to click a download link before actually downloading the PDF would make more sense (this is also what the documentation says).

**Comment by hawkeye64** [comment]
Thanks for bringing this up. I'll do some testing and see if I can come up with a solution.

FYI, another big issue is Electron as they also don't support inline PDF.

**Comment by hawkeye64** [comment]
k, I've looked into the code and when the browser does not support inline PDF, then text ("This browser does not support PDFs. Download the PDF to view it:") followed by a link. There is nothing there that would cause it to automatically download.
I'm not refuting this is happening, just saying it's not anything I'm controlling in the code.
