### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by iang0ld** [quasarframework/app-extension-qpdfviewer#29]
Add button for printing the pdf.

**Comment by hawkeye64** [comment]
?????

**Comment by iang0ld** [comment]
I looked and could not find a button to print the pdf being viewed.  Did I miss something?  Is this out of scope? Should I have taken more time to craft this a formal request? If so, I apologise.

**Comment by hawkeye64** [comment]
![image](https://user-images.githubusercontent.com/10262924/65922284-06cfce80-e3a2-11e9-86ee-449fd08f2802.png)

**Comment by iang0ld** [comment]
Thanks. I missed that. Appreciate the help :)
