### ISSUE TITLE
Error on running demo

### ISSUE THREAD

**Issue by lombo75** [quasarframework/app-extension-qpdfviewer#33]
Error in v-on handler: "TypeError: handler.apply is not a function"

found in

---> <QPdfviewer>
       <QPage>
         <Html5Example4> at src/examples/Html5Example4.vue
           <QCard>
             <ExampleCard> at src/components/ExampleCard.vue
               <Hero> at src/components/Hero.vue
                 <Examples> at src/pages/Examples.vue
                   <QPageContainer>
                     <QLayout>
                       <MainLayout> at src/layouts/MainLayout.vue
                         <App> at src/App.vue
                           <Root>

**Comment by mickey58github** [comment]
I get the same message as a warningr: [Vue Warn]: "Error in v-on handler: "TypeError: handler.apply is not a function".

Not sure what is causing it. My test PDF is correctly displayed, so the qpdfviewer is working in general, except for this warning in the browser console.

**Comment by robsoncombr** [comment]
Hello, I also experienced this problem, I have some further information.
When I use the component in dev mode the problem does not occur, after build it to production it happens, however the component works and the pdf is showed.

Message on console:

TypeError: e.apply is not a function
    at nt (vendor.e45766d5.js:2)
    at HTMLObjectElement.r (vendor.e45766d5.js:2)
    at HTMLObjectElement.Bs.s._wrapper (vendor.e45766d5.js:2)

**Comment by mickey58github** [comment]
I get the above warning in dev mode, I have not tried it in production mode yet.

**Comment by hawkeye64** [comment]
@robsoncombr @mickey58github @lombo75 Please specify which pdv viewer you were using. Thanks.

**Comment by tof06** [comment]
@hawkeye64 I have the same problem... 
I'm using `html5` pdf viewer. Tried with `pdfjs`, it works fine.
Error message occurs in Firefox & Chrome (both in their latest version). Didn't try in IE.

You can reproduce on the [demo page](https://quasarframework.github.io/app-extension-qpdfviewer/examples). Just open the page & your devtools console.

Thanks.

**Comment by Cmacu** [comment]
I am getting the same error when using the default `html5` viewer.

**Comment by abrahamPYW** [comment]
I am getting the same error

**Comment by mickey58github** [comment]
I have uninstalled my original QPdfViewer package, and reinstalled the latest one. 

I'm still getting this strange error in the Chrome browser log when using <q-pdfviewer type="html5> in my code - although the rest of QPdfViewer works correctly:

v-on handler: "TypeError: handler.apply is not a function" found in
---> <QPdfviewer>

**Comment by hawkeye64** [comment]
I think they are conflicting. I am about ready to slice pdfjs out of the original QPdfViewer. It was supposed to be simplistic and light weight.

**Comment by hawkeye64** [comment]
https://github.com/quasarframework/app-extension-qpdfviewer/issues/45

**Comment by mickey58github** [comment]
I prefer html5 over pdfjs , so in general no issue with removing pdfjs, except, iif you remove the pdfjs, I'm left with the above error (which might be non-critical, because the viewer works even with the error).

**Comment by kirame09** [comment]
Any solution for this one?

**Comment by hawkeye64** [comment]
I am trying to find time. I have 4 major projects on the go right now, and with covid-19, everyone is on edge and breathing down my neck. I will get to it as soon as I can, and PRs are also welcomed.

**Comment by Stjefan** [comment]
Jeff, thanks. No worries, from my end this is not an urgent problem. Stay healthy!

**Comment by hawkeye64** [comment]
We, like most others, I presume, are now in isolation. Current theory is this will last 2-3 months. :(

**Comment by hawkeye64** [comment]
Well, it's lasted much longer than anticipated. In the meantime, QPdfviewer now supports Quasar v2/Vue v3.
Install with:
```
quasar ext add @quasar/qpdfviewer@next
```
Notice the `@next` on the end.
New docs are found here: https://qpdfviewer.netlify.app/

If anyone still have the same issues, please report in a new issue. Thank you.

**Comment by mickey-bimlive** [comment]
:-) Jeff, thanks for your work and continuity following up even on older issues.
