### ISSUE TITLE
Error when trying to load pdfjs example

### ISSUE THREAD

**Issue by lombo75** [quasarframework/app-extension-qpdfviewer#34]
Does anyone know what causes this error, it has something to do with the url(src) i am passing in

PDF.js v2.1.266 (build: 81f5835c)
Message: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

When I enter http://localhost:8080/statics/pdf/pdf-test.pdf in browser the pdf displays

but when I enter this url as src I get this error

console errors:

Uncaught SyntaxError: Invalid left-hand side in assignment
viewer.js:1035 Uncaught (in promise) Error: An error occurred while loading the PDF.
    at viewer.js:1035
(anonymous) @ viewer.js:1035
load (async)
(anonymous) @ pdf.js:12907
loadScript @ pdf.js:12904
loader @ pdf.js:10602
setupFakeWorkerGlobal @ pdf.js:10607
_setupFakeWorker @ pdf.js:10776
terminateEarly @ pdf.js:10690
onWorkerError @ pdf.js:10696
error (async)
_initialize @ pdf.js:10700
PDFWorker @ pdf.js:10653
getDocument @ pdf.js:9660
_callee7$ @ viewer.js:993
tryCatch @ viewer.js:2720
invoke @ viewer.js:2895
prototype.<computed> @ viewer.js:2763
asyncGeneratorStep @ viewer.js:332
_next @ viewer.js:334
(anonymous) @ viewer.js:334
(anonymous) @ viewer.js:334
open @ viewer.js:1048
webViewerOpenFileViaURL @ viewer.js:1882
webViewerInitialized @ viewer.js:1856
Promise.then (async)
run @ viewer.js:770
webViewerLoad @ viewer.js:258

**Comment by hawkeye64** [comment]
@lombo75 You need to show some code.
This error message is suspect of a devland error:
```
Uncaught SyntaxError: Invalid left-hand side in assignment
```
