### ISSUE TITLE
Can only view first page on capacitor

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-qpdfviewer#47]
Somehow I can only view the first page of a PDF on Capacitor.

**Comment by hawkeye64** [comment]
pdfjs is scheduled to be deprecated @mesqueeb Try integrating it yourself for better manipulation of the component.

**Comment by mesqueeb** [comment]
@hawkeye64 I ended up opening the "url" of where the PDF is uploaded with the in-app browser in Capacitor.
It works like a charm. ;)
