### ISSUE TITLE
Feature: PDF.js Support

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/app-extension-qpdfviewer#5]
## The need for a PDF renderer library
Currently, this extension only makes use of native capabilities and fallbacks of the browsers. Sometimes this is not enough, and we want to display the PDF somehow even if the browser can't render inline PDF, or maybe have control on the pdf viewer, provide custom UI for the viewer, etc. This is where [PDF.js](https://mozilla.github.io/pdf.js/) comes into play.

> ### PDF.js
> A general-purpose, web standards-based platform for parsing and rendering PDFs.

With this feature, full-blown document viewers could be built with Quasar.

## Implementing it
This will be a huge improvement and will require a lot of work (compared to the work done with the current feature set). I found some resources that can give many ideas about implementing it in Vue, also provide a base point.

There is a [repository](https://github.com/rossta/vue-pdfjs-demo) that contains a Vue app with [PDF.js](https://github.com/mozilla/pdf.js/) demo. Also, there is a detailed series of posts named [Building a PDF Viewer with Vue.js](https://rossta.net/blog/series/pdf-viewer.html), which tells about the adventure of that demo repository.

## Some ideas
One or more of these ideas can be implemented together.
- We can offer this feature set optionally with [Prompts API](https://quasar.dev/app-extensions/development-guide/prompts-api) to reduce the dependencies for those who don't want this.
- We can provide (a) separate component(s) that uses PDF.js while also keeping the current behavior separately.
    - We can provide a UI built with Quasar's lovely components over the rendered PDF. (Like app-extension-qmediaplayer does on the native `media` tags)
- We can add a prop to the current component to serve this feature set as a fallback(instead of the unsupported text which is the current last fallback).

**Comment by hawkeye64** [comment]
This is a great idea! Hoping PDF.js supports being run in Electron, as that would be great.
:heart: Thanks for letting me know about this library.

**Comment by yusufkandemir** [comment]
@hawkeye64 judging from the existence of

> #### [How to Build a PDF Viewer with Electron and PDF.js](https://www.pdftron.com/blog/electron/how-to-build-an-electron-pdf-viewer/)

and

> #### [Electron-PDF-Viewer](https://github.com/praharshjain/Electron-PDF-Viewer)
> PDF viewer, created using Electron framework and PDF.js

I think I can say it must work on Electron.

**Comment by SmellydogCoding** [comment]
I would really love to see this as well.  Having to rely on end users having the right apps (mobile) or extensions installed, or having to build a separate viewer for Electron kinda defeats Quasars purpose of deploying to multiple platforms from a single code base.

I've used pdfvuer with VueJS but I can't get it working with Quasar.  I think there is a problem with PDF JS and the Window object but I'm not sure.

**Comment by hawkeye64** [comment]
I started investigating this as a possible solution. Hope to have a remedy soon.

**Comment by SmellydogCoding** [comment]
I believe I've found a solution.  I used this to implement pdfvuer, but hopefully it will solve the dreaded "referenceError: window is not defined" in other libraries using PDF JS.

Add this to the build section of your quasar.conf.js:

`
build: {
  chainWebpack (chain) {
    chain.output.globalObject('this')
  }
}
`

**Comment by rconstantine** [comment]
@hawkeye64 , I hope as you make the change that you can retain support for blobs per: https://forum.quasar-framework.org/topic/3551/quasar-qpdfviewer-v1-0-0-beta-2-release

Thanks!

**Comment by hawkeye64** [comment]
added in v1.0.0-beta.4
@rconstantine PDFJS does not do blobs, but now you can decide which rendering engine to use. So, still available when `type="html5"`.

**Comment by danicholls** [comment]
Just noting the release said it was tested on SPA, SSR, and Electron. Will Cordova be included?

**Comment by hawkeye64** [comment]
@danicholls If you are using Cordova, you are welcome to test. Those are just the three I was able to do quickly. In truth, I have never done a cordova app. I should learn, so I can test that as well.

**Comment by dev-steverob** [comment]
I have tested and PDFJS does seem to work with blobs? I'm creating PDF's on the fly using jsPDF and outputting as a blob and then viewing with your plugin and view type=pdfjs so I get the better functionality.

### HTML
```
<q-pdfviewer
  v-model="show"
  :src="pdf"
  type="pdfjs"
  content-class="fit container"
  inner-content-class="fit container"
/>
```

### SCRIPT
```
pdfOutput () {
  var doc = new JsPDF()
  let address = [
    this.start.COMPANY_NA,
    this.start.SITE_ADDRE,
    this.start.SITE_ADDR2,
    this.start.SITE_CITY,
    this.start.SITE_POSTC
  ]
  doc.text(address, 15, 15)

  let pdf = doc.output('blob', { filename: 'pdfTest.pdf' })
  this.pdf = window.URL.createObjectURL(pdf)
}
```
