### ISSUE TITLE
How to manipulate pdf.js options (or iframe content)?

### ISSUE THREAD

**Issue by nulele** [quasarframework/app-extension-qpdfviewer#54]
Hello,

I'd like to hide/remove the right panel button in the top right corner... any idea how to do it?

Thanks

UPDATE: currently I managed to hide the sidebar by commenting some code inside src/statics/pdfjs/web/viewer.html... but I'd prefere a more elegant way to do it... :P

**Comment by hawkeye64** [comment]
@nulele pdfjs is scheduled to be deprecated in the pdf viewer app-extension. Try integrating it yourself for better manipulation.

**Comment by nulele** [comment]
> @nulele pdfjs is scheduled to be deprecated in the pdf viewer app-extension. Try integrating it yourself for better manipulation.

DOH!!! I'ts a shame... it works perfectly for me! So your plan is to keep the html5 only type?

**Comment by hawkeye64** [comment]
@nulele Actually, we have been discussing of making a QPdfviewLight that only contains the HTML5 pdf viewer and keep the pdf.js in this one.

You can discuss here: https://github.com/quasarframework/app-extension-qpdfviewer/issues/45

**Comment by hawkeye64** [comment]
Both native HTML5 PDF viewer and PDFjs are available.
Manipulations on the PDFjs toolbar cannot be made at this time. You would have to integrate PDFjs viewer and do that work yourself.
