### ISSUE TITLE
pdfjs location for q/app v2

### ISSUE THREAD

**Issue by alexdee2007** [quasarframework/app-extension-qpdfviewer#59]
q/app v2 introduces new /public folder which replaces /src/statics 
So pdfjs location for this version should be /public rather than /src/statics ...

**Comment by kikan** [comment]
I reinstalled the extension 
```sh
quasar ext add @quasar/qpdfviewer
```

which copied the files in the old src/statics/ and then I did a symlink 

```sh
ln -s ../src/statics public/
```
It helps qpdfviewer find `pdfjs` folder and files, but it's clearly just a trick while waiting for a new version of the extension.

**Comment by alexdee2007** [comment]
Yes, I did something like this, using the postinstall script.
But you're right, it's just a temporary trick...

**Comment by captainjapeng** [comment]
I've created PR https://github.com/quasarframework/app-extension-qpdfviewer/pull/60 for @quasar/app v2 support.

**Comment by hawkeye64** [comment]
Will have a release some time today

**Comment by hawkeye64** [comment]
in v1.0.0-beta.8
