### ISSUE TITLE
qpdfviewer ios build error

### ISSUE THREAD

**Issue by vshepel16** [quasarframework/app-extension-qpdfviewer#61]
In the compiled application with the freshest packages of the quasar, the qpdfviewer error occurs on the ios device (and xcode emulator) and only in the assembled application, in dev mode it works fine.

Version: 
"quasar": "1.12.13"
"@quasar/app": "2.0.0"
"@quasar/quasar-app-extension-qpdfviewer": "1.0.0-beta.8"

![image](https://user-images.githubusercontent.com/23277509/89496641-63bac300-d7c3-11ea-9b37-be3c27881df0.png)

**Comment by hawkeye64** [comment]
@vshepel16 This isn't really enough to go on. :(
Will re-open if you can give more infomation.

**Comment by vshepel16** [comment]
Earlier, namely on July 6 (packages versions up to this point), after quasar build -m ios qpdfviewer on xcode emulator and real device showed a pdf document. Now, after updating quasar to version 2.0.x, everything works as before, only qpdfviewer does not display the document and only shows an error. The most interesting thing is that quasar dev -m ios --ide works as before, no errors. On android devices works fine.

My html:
          <q-pdfviewer
            v-show="isPdfLoaded"
            :value="true"
            :src="documentUrl"
            type="pdfjs"
          />

**Comment by hawkeye64** [comment]
@vshepel16 Sorry, no ideas. You will have to ask the pdfjs developers on this one.

**Comment by vshepel16** [comment]
The problem is in the build, because I get the wrong url URL.createObjectURL(blobDocument) before it have been added to qpdfviewer as :src. Pdfjs has nothing to do with it

**Comment by vshepel16** [comment]
Error in cordova-plugin-wkwebview-engine for switching to iOS WkWebView
https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Option-2%3A-Cordova-WkWebviewEngine-Plugin

Should use https://quasar.dev/quasar-cli/developing-cordova-apps/preparation#Option-1%3A-Ionic-Webview-Plugin , is works fine!

**Comment by hawkeye64** [comment]
@vshepel16 Glad to hear you got it resolved!
Btw, if you hadn't heard, Adobe is dropping support for Cordova. Try using Capacitor instead.
