### ISSUE TITLE
Newbie question: pdf 404- Nothing there

### ISSUE THREAD

**Issue by garymazz** [quasarframework/app-extension-qpdfviewer#68]
Hi 

I'm new to quasar and using the extension. Webpack shows me no love omitting my pdf and I get a 404 error. I'm assuming the path is not correct.

I'm running:
  Running @quasar/cli v1.1.2
  Running @quasar/app v2.0.8

In the build section of quasar.conf.js, I placed line publicPath: 'app-extension-qpdfviewer',

I have tried placing the pdf in directories:
<project>/public/pdf
<project>/src/assets

I've also tried using the '~' webpack prefix, still no joy. 
My code is lifted from the qpdfviewer doc. 

What an I doing wrong ? :

```
<template>
  <q-page class="flex flex-center">
    <q-pdfviewer
      v-model="show"
      type="html5"
      :src="updatedSrc"
      content-class="absolute"
    />
  </q-page>
</template>

<script>
export default {
  data () {
    return {
      show: true,
      src: 'assets/license.pdf'
    }
  },
  computed: {
    updatedSrc () {
      if (process.env.MODE === 'electron') {
        return '/' + this.src
      }
      return this.src
    }
  }
}
</script>
```

**Comment by garymazz** [comment]
Not sure what happened, added this to package.json fixed the issue with path "pdf/license.pdf":
  "publishConfig": {
    "access": "public"} 

Maybe is needed a complete rebuild.

**Comment by hawkeye64** [comment]
@garymazz 
> in the build section of quasar.conf.js, I placed line publicPath: 'app-extension-qpdfviewer',

Don't do that. This is needed because the demo/docs site runs as https://quasarframework.github.io/app-extension-qpdfviewer/docs - using `publishPath` tells webpack to update urls/locations to add this to it otherwise none of the js, css or assets would be found.
