### ISSUE TITLE
Not display content when source is blob on ipad.

### ISSUE THREAD

**Issue by felek000** [quasarframework/app-extension-qpdfviewer#74]
Hello,
I want to display /download pdf html presentation.

First I download app
   ```
return axios({
      method: "get",
      url: URL,
      responseType: "blob",
    })
      .then((response) => {
        return {
          ...val,
          blob: response.data,
        };
      })
      .catch((_) => {
        onError(val);
      });
```

After that i save it and some other data related to indexDB.
```
  const { id } = dataToSave;
  return db.files.put(dataToSave, id);
```

I try open using few libs no results.
Also i have some standard code to run 
 ```
 const { title, blob, mimeType } = material;
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.style.display = "none";
  a.href = url;

  // the filename you want
  a.download = title;
  document.body.appendChild(a);
  a.click();

  setTimeout(() => {
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }, 1000);
```

Now i use qpdfviewer
        ```
<q-pdfviewer
          v-model="modalTmp"
          type="html5"
          :src="updatedSrc"
          content-class="absolute"
        />
```
I open file saved as blob ans pass as prop.
```
      const { title, blob, mimeType, url, fileType } = material;
      const newBlob = new Blob([blob], { type: mimeType });
      console.log(blob, newBlob);
      const blobURL = window.URL.createObjectURL(newBlob);
      this.updatedSrc = blobURL;
      this.modalTmp = true;
```

On the first time fresh refresh page and download files. The file shows. When i refresh page/press  button that filter data fromIndexDB. file not shows up. That happens only on Ipad. 
Any workaround this will be much appreciated.

**Comment by hawkeye64** [comment]
Sorry, I haven't a clue what's going on in regards to iPad

**Comment by felek000** [comment]
I found solution. If anyone need it. .. I think this is ipad bug. I solve it saving file not as blob but array buffer. Than on user request  convert to blob and download it like before. All done on fly in memory. Might not be best, but there was not any other way to load it on ios.
