### ISSUE TITLE
error and load do nothing

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-qpdfviewer#8]
I'm currently using a template like so, inside of a QDialog component:

```html
<q-dialog ref="dialog" @hide="onDialogHide" maximized>
  <div class="dialog-pdf">
    <q-btn
      icon="close"
      color="primary"
      class="_close-btn"
      round
      size="25px"
      @click.stop="Ok"
    />
    <q-pdfviewer
      :value="true"
      :src="src"
      :error="onError"
      :load="onLoad"
      content-class="fit _container"
      inner-content-class="fit _container"
    />
  </div>
</q-dialog>
```

However, the `onError` and `onLoad` functions don't get triggered.
I wanted to use these to add a QSpinner before the pdf is loaded properly. ;)

**Comment by mesqueeb** [comment]
I had a look at the code, and I don't think anything is triggering these events:

https://github.com/quasarframework/app-extension-qpdfviewer/blob/dev/src/component/QPdfviewer.js#L42

**Comment by hawkeye64** [comment]
Thanks for the comments. I am not entirely sure. It says the object tag has those events and fires them. I'll need to investigate this further.

**Comment by mesqueeb** [comment]
@hawkeye64 
thanks!!
I just wanted to show you, I got it working for the time being like so:

![2019-07-29 22 38 37](https://user-images.githubusercontent.com/3253920/62092776-70076880-b2b1-11e9-837c-3cee93102ee6.gif)

I was able to have it appear inside a QDialog plugin component ;)
it looks great!

The PDF is positioned absolute so goes on top of the spinner once it finishes loading.

**Comment by hawkeye64** [comment]
So, what's your fix to know when it is loaded?

Btw, you do some amazing and cool stuff with my AEs. :heart:

**Comment by mesqueeb** [comment]
@hawkeye64 I have the PDF on `position absolute` and therefore it appears above the spinner 🤣 

here's my complete QDialog component:
```html
<template>
<q-dialog ref="dialog" @hide="onDialogHide" maximized>
  <div class="dialog-pdf">
    <q-btn
      icon="close"
      color="primary"
      class="_close-btn"
      round
      size="25px"
      @click.stop="Ok"
    />
    <div class="_loading">
      <q-spinner size="20vw" color="primary" />
    </div>
    <q-pdfviewer
      :value="true"
      :src="src"
      :error="onError"
      :load="onLoad"
      content-class="_container"
      inner-content-class="fit"
    />
  </div>
</q-dialog>
</template>

<style lang="stylus" scoped>
// $

.dialog-pdf
  background white
  position relative
._container
  top 0
  position absolute
._close-btn
  position fixed
  z-index 2
  top 25px
  right 25px
._loading
  width 100vw
  height 100vh
  _flex column center center

</style>

<script>
import QDialogMethods from '~mixins/QDialogMethods'

export default {
  name: 'dialog-pdf',
  mixins: [ QDialogMethods ],
  props: {
    src: String,
  },
  computed:
  {
  },
  methods:
  {
    onError () {
      console.log('@ERROR', 'but this is not executed......')
    },
    onLoad () {
      console.log('@LOAD', 'but this is not executed......')
    },
  }
}
</script>
```

feel free to use a similar implementation for your DEMO app.
