### ISSUE TITLE
Package install of QPdfviewer v2.0.0 Alpha 1 not matching next branch

### ISSUE THREAD

**Issue by Brock-oly** [quasarframework/app-extension-qpdfviewer#96]
After installing:

quasar ext add @quasar/qpdfviewer@next

The following error:

Module not found: Can't resolve imported dependency "@quasar/quasar-app-extension-qpdfviewer/src/component/async.js"
Did you forget to install it? You can run: npm install --save @quasar/quasar-app-extension-qpdfviewer/src/component/async.js

in which the boot/qpdfviewer.js references:

import QPdfviewer from '@quasar/quasar-app-extension-qpdfviewer/src/component/async.js'

but in the Next branch it references:

import QPdfviewer from '@quasar/quasar-app-extension-qpdfviewer/src/component/QPdfviewer.js'

**Comment by hawkeye64** [comment]
@Brock-oly Thanks for letting me know about this. :heart: 
Fix is in v2.0.0-alpha.2
